# Default values for sg-todoapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageName: 'sabdhagiri/todoapp:3.0'
replicaCount: 3
configMapName: todoapp-config
secretName: todoapp-secret
dbHost: postgres.pg.svc.cluster.local

service:
    port: 80