apiVersion: v1
kind: ConfigMap
metadata:
  name: todoapp-config
data:
  .env.dev: |
    DB_HOST=postgres.pg.svc.cluster.local
    DB_PORT=5432
    DB_DATABASE=todoapp
    DB_USER=todoapp
    DEBUG=True
    SECRET_KEY=Sup3rS3cr3t
    SQLALCHEMY_TRACK_MODIFICATIONS=False