CREATE SCHEMA todoapp
    AUTHORIZATION todoapp;

ALTER DEFAULT PRIVILEGES IN SCHEMA todoapp
GRANT ALL ON TABLES TO todoapp;

ALTER DEFAULT PRIVILEGES IN SCHEMA todoapp
GRANT ALL ON SEQUENCES TO todoapp;

ALTER DEFAULT PRIVILEGES IN SCHEMA todoapp
GRANT EXECUTE ON FUNCTIONS TO todoapp WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA todoapp
GRANT USAGE ON TYPES TO todoapp WITH GRANT OPTION;